# https://www.capside.com/labs/deploying-full-django-stack-with-docker-compose/
version: '2'
services:
    # ----- DATABASE
    data:
        restart: always
        image: alpine
        volumes:
            - /var/lib/postgresql
        command: "true"

    postgres:
        restart: always
        image: postgres:latest
        volumes_from:
            - data
        volumes:
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./backups/postgresql:/backup
        env_file:
            - env
        expose:
            - "5432"

    # ----- CACHE
    redis:
        restart: always
        image: redis:latest
        expose:
            - "6379"

    # ----- PROXY
    nginx:
        restart: always
        build: ./nginx/
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - web
        links:
            - web:web

    # ----- WEBAPP
    migration:
        build: ./web/
        image: app
        command: sh -c "python /data/web/webapp/manage.py migrate"
        volumes:
            - ./web:/data/web
        links:
            - postgres:postgres
            - redis:redis
        depends_on:
            - postgres
        env_file: env

    web:
        restart: always
        expose:
            - "8000"
        links:
            - postgres:postgres
            - redis:redis
        env_file: env
        volumes:
            - ./web:/data/web
        #command: /usr/bin/gunicorn assetmanagement.wsgi:application -w 2 -b :8000
        command: python webapp/manage.py runserver 0.0.0.0:8000
        depends_on:
            - migration
        image: app
