version: '2'

services:
    # ------------------------------------------------------------------------------------
    # WEKAN - https://github.com/wekan/wekan-mongodb
    # ------------------------------------------------------------------------------------
    wekandb:
        # All Wekan data is stored in MongoDB. For backup and restore, see:
        #   https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data
        image: mongo:3.2.20
        container_name: wekan-db
        restart: always
        command: mongod --smallfiles --oplogSize 128
        networks:
            - wekan-tier
        expose:
          - 27017
        volumes:
            - /docker/data/wekan_bookstack/wekan-db:/data/db
            - /docker/data/wekan_bookstack/wekan-db-dump:/dump

    wekan:
        image: quay.io/wekan/wekan
        container_name: wekan-app
        restart: always
        networks:
            - wekan-tier
        # For running Wekan in different port like 3000, use: 3000:80
        ports:
            - 9001:8080
        environment:
            #---------------------------------------------------------------
            # == ROOT_URL SETTING ==
            # Change ROOT_URL to your real Wekan URL, for example:
            #   http://example.com
            #   http://example.com/wekan
            #   http://192.168.1.100
            #---------------------------------------------------------------
            - ROOT_URL=http://127.0.0.1:9001/
            #---------------------------------------------------------------
            # == PORT SETTING ==
            # Not needed on Docker, but if you had installed from source,
            #   you could also have setup Wekan Node.js port at localhost
            #   with setting: PORT=3001
            #   and have Nginx proxy to port 3001, see Wekan wiki.
            #---------------------------------------------------------------
            # - PORT=3001
            #---------------------------------------------------------------
            # == MONGO URL AND OPLOG SETTINGS ==
            # https://github.com/wekan/wekan-mongodb/issues/2#issuecomment-378343587
            # We've fixed our CPU usage problem today with an environment
            # change around Wekan. I wasn't aware during implementation
            # that if you're using more than 1 instance of Wekan
            # (or any MeteorJS based tool) you're supposed to set
            # MONGO_OPLOG_URL as an environment variable.
            # Without setting it, Meteor will perform a pull-and-diff
            # update of it's dataset. With it, Meteor will update from
            # the OPLOG. See here
            #   https://blog.meteor.com/tuning-meteor-mongo-livedata-for-scalability-13fe9deb8908
            # After setting
            # MONGO_OPLOG_URL=mongodb://<username>:<password>@<mongoDbURL>/local?authSource=admin&replicaSet=rsWekan
            # the CPU usage for all Wekan instances dropped to an average
            # of less than 10% with only occasional spikes to high usage
            # (I guess when someone is doing a lot of work)
            #---------------------------------------------------------------
            - MONGO_URL=mongodb://wekandb:27017/wekan
            #---------------------------------------------------------------
            # - MONGO_OPLOG_URL=mongodb://<username>:<password>@<mongoDbURL>/local?authSource=admin&replicaSet=rsWekan
            #---------------------------------------------------------------
            # == EMAIL SETTINGS ==
            # Email settings are required in both MAIL_URL and Admin Panel,
            #   see https://github.com/wekan/wekan/wiki/Troubleshooting-Mail
            #   For SSL in email, change smtp:// to smtps://
            # NOTE: Special characters need to be url-encoded in MAIL_URL.
            #---------------------------------------------------------------
            #- MAIL_URL=smtp://user:pass@mailserver.example.com:25/
            #- MAIL_FROM='Example Wekan Support <support@example.com>'
        depends_on:
            - wekandb

    # --------------------------------------------------------------------------------------
    # BOOKSTACK - https://github.com/solidnerd/docker-bookstack
    # --------------------------------------------------------------------------------------
    mysql:
        container_name: bookstack-db
        image: mysql:5.7.21
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=bookstack
            - MYSQL_USER=bookstack
            - MYSQL_PASSWORD=secret
        volumes:
            - /docker/data/wekan_bookstack/mysql-data:/var/lib/mysql
        networks:
            - wekan-tier

    bookstack:
        container_name: bookstack-app
        image: solidnerd/bookstack:0.21.0
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql:3306
            - DB_DATABASE=bookstack
            - DB_USERNAME=bookstack
            - DB_PASSWORD=secret
        volumes:
            - /docker/data/wekan_bookstack/bookstack_uploads:/var/www/bookstack/public/uploads
            - /docker/data/wekan_bookstack/bookstack_storage-uploads:/var/www/bookstack/public/storage
        ports:
            - 9002:80
        networks:
            - wekan-tier

# ----------------------------------------------------------------------------------------
# NETWORKS
# ----------------------------------------------------------------------------------------
networks:
    wekan-tier:
