---
tools_dir: /opt
home_dir: /root

kali_users:
  - name: marco
    comment: "Marco L."
    shell: /bin/bash

# kali_user_keys:
#   - name: marco
#     ssh_key: "ssh-rsa ..."

#kali_make_dirs:

kali_apt:
  - mlocate
  - zsh
  - ufw

#kali_pip:

#kali_easy_install:

#kali_gem:

#kali_go:

#kali_go_build:

#kali_git_repositories:

#kali_shortcuts:

kali_binary:
  - url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh

#kali_tars:

kali_config:
  - src: custom.zsh-theme
    dest: /root/.oh-my-zsh/themes/custom.zsh-theme

kali_templates:
  - src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
  - src: issue.ssh.j2
    dest: /etc/issue.ssh
    mode: "0644"
  - src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
  - src: zshrc.j2
    dest: /root/.zshrc
    mode: "0644"

kali_bash:
  - gnome3.sh
  - thunar.sh
  - bash.sh


# ----------------------------------------------------------------------------------------
# SSH CONFIG
# ----------------------------------------------------------------------------------------
sshd_banner: /etc/issue.ssh
sshd_ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
sshd_gssapiauthentication: "no"
sshd_hostkeyalgorithms: "ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa"
sshd_kexalgorithms: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
sshd_moduli_remove:
  - 1023
  - 1535
sshd_passwordauthentication: "yes"
sshd_permitemptypasswords: "no"
sshd_permitrootlogin: "yes"
sshd_pubkeyauthentication: "yes"
sshd_rsaauthentication: "yes"
sshd_usedns: "no"
sshd_usepam: "yes"
sshd_x11forwarding: "no"
