---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - kali-os
    - golang
    - kali-sw
    - kali-metasploit
  vars:
    - hostname: "attacker_kali"
    - kali_ufw_tcp_allow:
        - 22
  environment:
    PIPENV_VENV_IN_PROJECT: true
