---
# ----------------------------------------------------------------------------------------
# PREPARE
# ----------------------------------------------------------------------------------------
- name: Create directories
  register: dir_done
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ kali_make_dirs|default([]) }}"


# ----------------------------------------------------------------------------------------
# INSTALL
# ----------------------------------------------------------------------------------------
- name: Install Tools via APT
  apt: name={{item}} state=present
  sudo: true
  register: apt_done
  with_items:
    - bridge-utils            # Bridge network interfaces
    #- reaver                  # WPS pin brute force
    #- pixiewps                # Pixie Attack
    #- bully                   # WPS pin brute force
    - wifite                  # Automated Wi-Fi tool
    - mitmf                   # Framework for MITM attacks
    - fruitywifi              # Wireless network auditing tool
    - mana-toolkit            # Rogue AP for MITM Wi-Fi
    - aircrack-ng             # Wi-Fi cracking suite

- name: Install GIT repositories
  register: git_done
  git:
    repo={{ item.repo }}
    dest={{tools_dir}}/{{ item.dest }}
    accept_hostkey=yes
    version={{ item.version|default(\"master\") }}
    force={{ item.force|default("no") }}
  with_items:
    - "{{ kali_git_repositories|default([]) }}"

- name: Install shortcuts
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: a+x
  with_items:
    - wifiphisher


# ----------------------------------------------------------------------------------------
# CONFIGURE
# ----------------------------------------------------------------------------------------
- name: Configure mana-toolkit
  when: apt_done is success
  script: ../files/mana.sh

- name: Configure aircrack-ng
  when: apt_done is success
  script: ../files/aircrack.sh


# ----------------------------------------------------------------------------------------
# CLEANUP
# ----------------------------------------------------------------------------------------
- name: Clean the system
  script: ../files/cleanup.sh